const AuditAction = Object.freeze({
  LOGIN: 'LOGIN',
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_ROLE_CHANGED: 'USER_ROLE_CHANGED',
  USER_PERMISSION_CHANGED: 'USER_PERMISSION_CHANGED',
  PROCESS_CREATED: 'PROCESS_CREATED',
  PROCESS_UPDATED: 'PROCESS_UPDATED',
  PROCESS_STATUS_CHANGED: 'PROCESS_STATUS_CHANGED',
  PROCESS_DELETED: 'PROCESS_DELETED',
  PROCESS_ASSIGNED: 'PROCESS_ASSIGNED',
  DOCUMENT_ADDED: 'DOCUMENT_ADDED',
  LEGAL_EVENT_CREATED: 'LEGAL_EVENT_CREATED',
});

const AuditEntityType = Object.freeze({
  USER: 'USER',
  CLIENT: 'CLIENT',
  PROCESS: 'PROCESS',
  DOCUMENT: 'DOCUMENT',
  LEGAL_EVENT: 'LEGAL_EVENT',
  SYSTEM: 'SYSTEM',
});

const LegalEventType = Object.freeze({
  PROCESS_CREATED: 'PROCESS_CREATED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  DOCUMENT_ADDED: 'DOCUMENT_ADDED',
  LAWYER_ASSIGNED: 'LAWYER_ASSIGNED',
  NOTE_ADDED: 'NOTE_ADDED',
  INTERNAL_MOVEMENT: 'INTERNAL_MOVEMENT',
  CLIENT_CONTACT: 'CLIENT_CONTACT',
});

module.exports = {
  AuditAction,
  AuditEntityType,
  LegalEventType,
};
